export const DEPARTMENTS = [
    'Civil Engineering',
    'Mechanical Engineering',
    'Electrical Engineering',
    'Electronics Engineering',
    'Chemical Engineering',
    'Computer Science & Engineering',
    'Information Technology',
    'Electronics & Telecommunication Engineering',
    'Automobile Engineering',
    'Artificial Intelligence',
    'Artificial Intelligence & Data Science',
    'Artificial Intelligence & Machine Learning',
    'Computer Science & Design',
    'Computer Science & Business Systems',
    'Internet of Things',
    'Mathematics & Computing',
    'IT (AI & Robotics)',
    'Electrical Engineering (IoT)',
    'Computer Science & Technology',
];
